//! Decoded instruction type for the CPU executor.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Instruction {
    Nop,
    Hlt,
    Mov  { rd: u8, rs: u8 },
    Ldi  { rd: u8, imm: u32 },
    Ld   { rd: u8, rs: u8 },
    St   { rd: u8, rs: u8 },
    Ldb  { rd: u8, rs: u8 },
    Stb  { rd: u8, rs: u8 },
    Add  { rd: u8, rs: u8 },
    Sub  { rd: u8, rs: u8 },
    And  { rd: u8, rs: u8 },
    Or   { rd: u8, rs: u8 },
    Xor  { rd: u8, rs: u8 },
    Not  { rd: u8 },
    Shl  { rd: u8, rs: u8 },
    Shr  { rd: u8, rs: u8 },
    Addi { rd: u8, imm: u32 },
    Subi { rd: u8, imm: u32 },
    Andi { rd: u8, imm: u32 },
    Ori  { rd: u8, imm: u32 },
    Xori { rd: u8, imm: u32 },
    Mul  { rd: u8, rs: u8 },
    Div  { rd: u8, rs: u8 },
    Mod  { rd: u8, rs: u8 },
    Cmp  { rd: u8, rs: u8 },
    Cmpi { rd: u8, imm: u32 },
    Push { rs: u8 },
    Pop  { rd: u8 },
    Call { addr: u32 },
    Ret,
    Jmp  { addr: u32 },
    Jz   { addr: u32 },
    Jnz  { addr: u32 },
    Jc   { addr: u32 },
    Jnc  { addr: u32 },
    Jn   { addr: u32 },
    Jnn  { addr: u32 },
    Jv   { addr: u32 },
    Jnv  { addr: u32 },
    Jgt  { addr: u32 },
    Jlt  { addr: u32 },
    Jge  { addr: u32 },
    Jle  { addr: u32 },
    In   { rd: u8, port: u32 },
    Out  { rs: u8, port: u32 },

    Fadd  { rd: u8, rs: u8 },
    Fsub  { rd: u8, rs: u8 },
    Fmul  { rd: u8, rs: u8 },
    Fdiv  { rd: u8, rs: u8 },
    Fmod  { rd: u8, rs: u8 },
    Fneg  { rd: u8 },
    Fabs  { rd: u8 },
    Fsqrt { rd: u8 },
    Fcmp  { rd: u8, rs: u8 },
    Ftoi  { rd: u8 },
    Itof  { rd: u8 },
    Fldi  { rd: u8, imm: u32 },
}
